baseURL = "https://menziess.github.io"
themesDir = "themes"
languageCode = "en-us"
title = "menziess blog"
theme = "hugo-whisper-theme"
publishdir = "menziess.github.io"
paginate = "10" # Number of posts per page
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id
